# Generated by Django 5.2.14 on 2026-05-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="echohistory", name="image_url",),
        migrations.AddField(
            model_name="echohistory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="history_results/", verbose_name="結果圖片"
            ),
        ),
    ]
